### PR TITLE
Simplified Chinese translation

### PR DESCRIPTION
**Pull request by ybw0014**

### CODE REVIEW

**Comment by JustAHuman-xD** [comment]
Do you want me to setup a translation system for the data.json, I can rq that way you can translate item names

**Comment by ybw0014** [comment]
> Do you want me to setup a translation system for the data.json, I can rq that way you can translate item names

There is a simplified Chinese version of Slimefun that items are all translated, so it would be easier if we can use the generator to generate own data.

**Comment by JustAHuman-xD** [comment]
Oh yeah that would work! Ill work on a translation system for data.json then

**Comment by JustAHuman-xD** [comment]
Closing this as everything is being re-written, feel free to make one pertaining to the rewrite when it is finished!

**Pull request closed without merging**
