### PR TITLE
Add support for Chinese (Simplified)

### PR DESCRIPTION
**Pull request by RawDiamondMC**
Progress:
- [x] Translate
- [ ] ~_Test in game_~ should have no problem
Note:
Addons names are from @SlimefunGuguProject

### CODE REVIEW

**Comment by JustAHuman-xD** [comment]
Do you have discord? I saw that you commented on some commits but GitHub won't show them to me.

**Comment by RawDiamondMC** [comment]
> Do you have discord? I saw that you commented on some commits but GitHub won't show them to me.

I don't use Discord much because I'm a Chinese:(

Code from build.gradle

```
tasks.register('copyJar', Copy) {
    from 'C:/Users/keena/Documents/GitHub/SlimefunEssentials/build/libs/Slimefun Essentials-2.4.jar'
    into 'C:/Users/keena/curseforge/minecraft/Instances/Testing (1.19.3)/mods'
    new File('C:/Users/keena/curseforge/minecraft/Instances/Testing (1.19.3)/config', "slimefun_essentials_restart.txt").text = ""
}

assemble.finalizedBy(copyJar)
```
These test codes should not be pushed to github, as this will cause it to fail to build on other machines (because gradle cannot find "C:/Users/keena/curseforge/minecraft/Instances/Testing (1.19.3)/mods" on other machines).

**Comment by JustAHuman-xD** [comment]
Ah, got it. Yeah I will remove it soon just doing it for testing purposes on my machine

**Comment by haiman233** [comment]
There are some inconsistencies in the translation of category names, so I will correct them.

**Pull request closed without merging**
