### PR TITLE
Some improvements(maybe)

### PR DESCRIPTION
**Pull request by RawDiamondMC**
- Update to gradle 8.1.1.
- Change "fabric" to "fabric-api" in fabric.mod.json.
- Update depends.
- Update mappings.
- Add actions to auto build.

### CODE REVIEW

**Comment by JustAHuman-xD** [comment]
The testing code will be removed by me after the main rewriting is done, but it shouldn't error on other computers. What error do you mean?

**Comment by RawDiamondMC** [comment]
> The testing code will be removed by me after the main rewriting is done, but it shouldn't error on other computers. What error do you mean?

No such file or directory
Gradle cannot find C:/Users/keena/curseforge/minecraft/Instances/Testing (1.19.3)/mods

**Comment by JustAHuman-xD** [comment]
As for the other changes after my next push I will probably merge 👍 though if you could exclude the removal of those testing changes for now that would be ideal

**Comment by RawDiamondMC** [comment]
I added the testing code back✔
Although Github Actions will run into errors until you remove the testing code.

**Comment by JustAHuman-xD** [comment]
Sounds good, once I'm done with the initial beta releases I'll merge this. Hopefully that will be very soon 🤞

**Pull request closed without merging**
